### ISSUE TITLE
Peer-to Peer Morning Session Code Review

### ISSUE THREAD

**Issue by jonathanmunamire** [wassimchakib/Free-Games-Tracker#26]
Hi @manq2010 , 

Your project is good to go, with all tasks up to date! And good header style! There is nothing else to say other than...  :shipit: 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Good Work Structure ✔️ 
- Good implementations  ✔️ 
- All Linters are Running  ✔️

Cheers and Happy coding!👏👏👏

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by BregornOriginal** [comment]
Hi @Team 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### ***You have submitted a project, that contains the wrong link on the submission. Please submit the link of the Pull Request instead of the Issue***

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
